version: '3.8'

services:
  bot:
    image: tomsh666/bot:latest
    depends_on:
      - model-api
    env_file:
      - app.env
    ports:
      - "8085:8085"
    restart: always
    networks:
      - app_network

  model-api:
    image: tomsh666/model-api:latest
    ports:
      - "8086:8086"
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
