name: CI/CD Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push bot image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bot:latest ./bot
          docker push ${{ secrets.DOCKER_USERNAME }}/bot:latest

      - name: Build and push model-api image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/model-api:latest ./model_api
          docker push ${{ secrets.DOCKER_USERNAME }}/model-api:latest
