name: Deploy Run

on:
  workflow_dispatch:

jobs:
  docker_run:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment variables (safe)
        run: |
          echo "MESSAGE_DB_PATH=${{ vars.MESSAGE_DB_PATH }}"
          echo "LISTENER_DB_PATH=${{ vars.LISTENER_DB_PATH }}"
      
      - name: Run Docker container
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            echo "MESSAGE_DB_PATH=${{ vars.MESSAGE_DB_PATH }}"
            echo "LISTENER_DB_PATH=${{ vars.LISTENER_DB_PATH }}"
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
            echo "CONTROL_CHAT_ID=${{ secrets.CONTROL_CHAT_ID }}"

            if [ "$(sudo docker ps -aq -f name=neuro_parse)" ]; then
              sudo docker stop neuro_parse || true
              sudo docker rm neuro_parse || true
            fi

            sudo docker run -d \
              --name neuro_parse \
              -p 8085:80 \
              -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              -e MESSAGE_DB_PATH=${{ vars.MESSAGE_DB_PATH }} \
              -e LISTENER_DB_PATH=${{ vars.LISTENER_DB_PATH }} \
              -e CONTROL_CHAT_ID=${{ secrets.CONTROL_CHAT_ID }} \
              -e TARGET_CHAT_ID=${{ secrets.TARGET_CHAT_ID }} \
              tomsh666/neuro_parse:latest
