name: Deploy Run

on:
  workflow_run:
    workflows: ["Deploy Pull"]
    types:
      - completed

jobs:
  docker_run:
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker container
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            sudo docker run -d \
              --name neuro_parse \
              -p 8085:80 \
              -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              -e MESSAGE_DB_PATH=${{ secrets.MESSAGE_DB_PATH }} \
              -e LISTENER_DB_PATH=${{ secrets.LISTENER_DB_PATH }} \
              -e CONTROL_CHAT_ID=${{ secrets.CONTROL_CHAT_ID }} \
              -e TARGET_CHAT_ID=${{ secrets.TARGET_CHAT_ID }} \
              tomsh666/neuro_parse:latest
            sudo docker ps | grep neuro_parse
