name: Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ steps.repo-path.outputs.path }}
    steps:
      - name: Checkout repo
        id: repo-path
        uses: actions/checkout@v3

  setup-docker:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  docker-login:
    needs: setup-docker
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-image:
    needs: docker-login
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: tomsh666/neuro_parse:latest

  push-image:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tomsh666/neuro_parse:latest

  deploy:
    needs: push-image
    runs-on: ubuntu-latest
    steps:
      - name: Stop old container
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: docker stop neuro_parse || true

      - name: Remove old container
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: docker rm neuro_parse || true

      - name: Run new container
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: docker run -d --name neuro_parse -p 8085:80 --env-file .env tomsh666/neuro_parse:latest

      - name: Check container status
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: docker ps | grep neuro_parse
