name: Deploy Pull

on:
  workflow_dispatch:

jobs:
  docker_pull:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            sudo docker stop neuro_parse || true
            sudo docker rm neuro_parse || true
            sudo docker pull --progress=plain tomsh666/neuro_parse:latest
