name: CI/CD Deploy

on:
  push:
    branches:
      - Tomsh666-patch-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check docker-compose
        run: ls -l ${{ github.workspace }}
      - name: Copy docker-compose to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "${{ secrets.DIR }}"
  
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            cd ${{ secrets.DIR }}
            docker-compose pull
            docker-compose up -d --remove-orphans
