name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Containers
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            cd /home/${{ secrets.HOST_USER }}

            export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            export MESSAGE_DB_PATH=${{ vars.MESSAGE_DB_PATH }}
            export LISTENER_DB_PATH=${{ vars.LISTENER_DB_PATH }}
            export CONTROL_CHAT_ID=${{ secrets.CONTROL_CHAT_ID }}
            export TARGET_CHAT_ID=${{ secrets.TARGET_CHAT_ID }}
            export MODEL_API_URL=${{ vars.MODEL_API_URL }}

            echo "Pulling images..."
            sudo docker-compose pull
            
            echo "Stopping old containers..."
            sudo docker-compose down
            
            echo "Starting containers..."
            sudo BOT_TOKEN=$BOT_TOKEN \
                 MESSAGE_DB_PATH=$MESSAGE_DB_PATH \
                 LISTENER_DB_PATH=$LISTENER_DB_PATH \
                 CONTROL_CHAT_ID=$CONTROL_CHAT_ID \
                 TARGET_CHAT_ID=$TARGET_CHAT_ID \
                 MODEL_API_URL=$MODEL_API_URL \
                 docker-compose up -d --remove-orphans
