name: Generate download command

on:
  workflow_dispatch:

jobs:
  generate-command:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          curl -L -o docker-compose.yml \
               https://raw.githubusercontent.com/UltraNeuroMegaCorp/NeuroParse/master/docker-compose.yml

