name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  create-env:
    name: Create .env on VM
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: SSH to VM and create .env
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            cd /root/snap
            sudo cat <<EOF > app.env
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            MESSAGE_DB_PATH=${{ vars.MESSAGE_DB_PATH }}
            LISTENER_DB_PATH=${{ vars.LISTENER_DB_PATH }}
            CONTROL_CHAT_ID=${{ secrets.CONTROL_CHAT_ID }}
            TARGET_CHAT_ID=${{ secrets.TARGET_CHAT_ID }}
            MODEL_API_URL=${{ vars.MODEL_API_URL }}
            EOF
            sudo chmod 600 app.env

  deploy:
    name: Deploy Containers
    runs-on: ubuntu-latest
    needs: create-env
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            cd /home/${{ secrets.HOST_USER }}

            echo "Pulling images..."
            sudo docker-compose --env-file /root/snap/app.env pull
            
            echo "Stopping old containers..."
            sudo docker-compose --env-file /root/snap/app.env down
            
            echo "Starting containers..."
            sudo docker-compose --env-file /root/snap/app.env up -d --remove-orphans

            echo "Deleting .env..."
            sudo rm -rf /root/snap/app.env
